### ISSUE TITLE
Missing config.json?

### ISSUE THREAD

**Issue by hopkinsjj9** [BlackCloudConcepts/geolocLang#1]
ENOENT: no such file or directory, stat 'C:\Users\Jack\Documents\redux\geolocLang-master\src\config.json'

**Comment by BlackCloudConcepts** [comment]
Yeah I did a .gitignore on it so I can store my api keys there.  You can add it yourself in src/config.json.

{
  "what_three_words_api_key" : "YOURKEYHERE"
}

You can get your key here.  http://developer.what3words.com/

Hope that helps.
